#ifndef WINOOW_UTILS_HPP
# define WINOOW_UTILS_HPP

# define INIT_FLAGS					SDL_INIT_AUDIO | SDL_INIT_TIMER | SDL_INIT_VIDEO | SDL_INIT_EVENTS
# define WINDOW_FLAGS				SDL_WINDOW_SHOWN | SDL_WINDOW_BORDERLESS | SDL_WINDOW_RESIZABLE
# define WINDOW_WIDTH				800
# define WINDOW_HEIGHT				500
# define WINDOW_POS_CENTER			(SDL_WINDOWPOS_CENTERED), (SDL_WINDOWPOS_CENTERED)
# define DELAY						5000
# define WINDOW_FULLSCREEN			SDL_WINDOW_FULLSCREEN
# define WINDOW_FULLSCREEN_DESKTOP	SDL_WINDOW_FULLSCREEN_DESKTOP
#endif
