#ifndef EVENTMANANGER_DEFINES_HPP
# define EVENTMANANGER_DEFINES_HPP

# include <SDL2/SDL_events.h>

// # define WINDOW_EVENT		SDL_WINDOWEVENT
// # define SYSWM_EVENT		SDL_SYSWMEVENT
// # define KEY_DOWN			SDL_KEYDOWN
// # define KEY_UP				SDL_KEYUP
// # define TEXT_EDITING		SDL_TEXTEDITING
// # define TEXT_INPUT			SDL_TEXTINPUT
// # define MOUSE_MOTION		SDL_MOUSEMOTION
// # define MOUSE_BUTTON_UP	SDL_MOUSEBUTTONUP
// # define MOUSE_BUTTON_DOWN	SDL_MOUSEBUTTONDOWN
// # define MOUSE_WHEEL		SDL_MOUSEWHEEL

#endif
